<?php
require_once('../libs/seguridad.php');
?>

<!DOCTYPE html>
<html lang="es">
    <!-- Head -->
    <head>
        <!-- Titulo -->
        <title>Titulo</title>
        <!-- Charset -->
        <meta charset="UTF-8">
        <!-- Viewport -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <!-- Boostrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/ >
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
        <link rel="stylesheet" href="../styles/css/alertify.bootstrap.css"/>
        <link rel="stylesheet" href="../styles/css/alertify.core.css">
        <link rel="stylesheet" href="../styles/css/alertify.default.css"/>
        <!-- Jquery css -->
        <link  href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/smoothness/jquery-ui.css"
        <!-- Estilos: en href va la hoja de estilos propia -->
        <link rel="stylesheet" href="../styles/css/styles.css">
    </head>

    <!-- Body -->
    <body>

        <h1>Bienvenido: <?php echo Session::getValue("inputId"); ?></h1>
        <!-- Scripts: jquery y bootstrap -->
        <script src="../styles/js/jquery.js"></script>
        <script src="../styles/js/bootstrap.min.js"></script>
        <script src="../styles/js/alertify.min.js"></script>
        <!-- Scripts propios -->
        <script src="../styles/js/buttonsActions.js"></script>
    </body>
</html>