<!DOCTYPE html>
<html lang="es">
    <!-- Head -->
    <head>
        <!-- Titulo -->
        <title>Titulo</title>
        <!-- Charset -->
        <meta charset="UTF-8">
        <!-- Viewport -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
        <!-- Boostrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/ >
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
        <link rel="stylesheet" href="../styles/css/alertify.bootstrap.css"/>
        <link rel="stylesheet" href="../styles/css/alertify.core.css">
        <link rel="stylesheet" href="../styles/css/alertify.default.css"/>
        <!-- Jquery css -->
        <link  href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/smoothness/jquery-ui.css"
        <!-- Estilos: en href va la hoja de estilos propia -->
        <link rel="stylesheet" href="../styles/css/styles.css">
    </head>

    <!-- Body -->
    <body>
        <h1 class="page-header" id="page-header">Bienvenido Estudiante</h1>
        <div class="row">
            <div class="col-sm-9 col-md-10">
                <div class="table" id="table">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>NOMBRE</th>
                                <th>CURSO</th>
                                <th>JORNADA</th>
                                <th>TIPO DOCUMENTO</th>
                                <th>DOCUMENTO</th>
                            </tr>
                        </thead>


                        <tbody>
                        <?php
                        require_once('../modules/EstudianteController.php');
                        $estudiante = new EstudianteController();
                        $resultArray = $estudiante->getEstudiante('1' ,'cc' ,'1234');

                        foreach($resultArray as $row) {
                        ?>
                            <tr>
                                <td><?php echo $row["id"];?></td>
                                <td><?php echo $row["nombre"];?></td>
                                <td><?php echo $row["curso"];?></td>
                                <td><?php echo $row["jornada"];?></td>
                                <td><?php echo $row["tipodcto"];?></td>
                                <td><?php echo $row["numdcto"];?></td>
                            </tr>
                        <?php }?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-sm-2 col-md-1 sidebar">
                <ul class="nav nav-sidebar">
                    <li>
                        <a href="http://localhost/proyecto_final_bd/views/indexEstudiantesNotas.phtml">Notas</a>
                    </li>
                    <li>
                        <a href="http://localhost/proyecto_final_bd/views/indexEstudianteHorario.phtml">Horario</a>
                   </li>
                </ul>
            </div>
        </div>    
        <!-- Scripts: jquery y bootstrap -->
        <script src="../styles/js/jquery.js"></script>
        <script src="../styles/js/bootstrap.min.js"></script>
        <script src="../styles/js/alertify.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
        <!-- Scripts propios -->
        <script src="../styles/js/buttonsActions.js"></script>
    </body>
</html>