<!DOCTYPE html>
<html lang="es">
    <!-- Head -->
    <head>
        <!-- Titulo -->
        <title>Información personal | Sistema de notas</title>
        <!-- Charset -->
        <meta charset="UTF-8">
        <!-- Viewport -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
        <!-- Boostrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/ >
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
        <link rel="stylesheet" href="../styles/css/alertify.bootstrap.css"/>
        <link rel="stylesheet" href="../styles/css/alertify.core.css">
        <link rel="stylesheet" href="../styles/css/alertify.default.css"/>
        <!-- Jquery css -->
        <link  href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/smoothness/jquery-ui.css"
        <!-- Estilos: en href va la hoja de estilos propia -->
        <link rel="stylesheet" href="../styles/css/styles.css">
    </head>

    <!-- Body -->
    <body>
        <h1 class="page-header">Bienvenido</h1>

        <form class="form-group" action="" name="frmProfesorInf" method="POST">
            <div class="row">
                <aside class="col-sm-3">
                    <ul class="btn-group">
                        <label for="btnInfo">
                            <input type="submit" class="btn btn-default"
                                   name="btnInfo" id="btnInfo" value="Información personal">
                        </label><br/>

                        <label for="btnGrupo">
                            <input type="submit" class="btn btn-default"
                                   name="btnGrupo" id="btnGrupo" value="Ver grupo">
                        </label><br/>

                        <label for="btnReporte">
                            <input type="submit" class="btn btn-default"
                                   name="btnReporte" id="btnReporte" value="Hacer reporte">
                        </label><br/>

                        <label for="btnInforme">
                            <input type="submit" class="btn btn-default"
                                   name="btnInforme" id="btnInforme" value="Informe">
                        </label><br/>
                    </ul>
                </aside>

                <div class="jumbotron col-sm-8">
                    <h1>Hello, world!</h1>
                    <p>...</p>
                    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
                </div>
            </div>


        </form>
        <!-- Scripts: jquery y bootstrap -->
        <script src="../styles/js/jquery.js"></script>
        <script src="../styles/js/bootstrap.min.js"></script>
        <script src="../styles/js/alertify.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
        <!-- Scripts propios -->
        <script src="../styles/js/buttonsActions.js"></script>
    </body>
</html>